name: Heladeria Tests

on: push

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flask selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Fix chromedriver symlink
        run: |
          if [ ! -f /usr/bin/chromedriver ]; then
            sudo ln -s /snap/bin/chromium.chromedriver /usr/bin/chromedriver
          fi

      - name: Start Flask App
        run: |
          nohup python app.py &
          sleep 5

      - name: Run Selenium Test
        run: python test_selenium.py

      - name: Success Message
        if: success()
        run: echo "Todos los tests pasaron."
